# Generated by Django 5.2.17 on 2026-09-05 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_text', models.CharField(help_text='The text shown to the reader for this option.', max_length=500)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order among sibling choices from the same source_node.')),
                ('requires_flag', models.CharField(blank=True, help_text='Optional gating condition — a flag that must be present in ReaderProgress.flags for this choice to appear.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_node', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='PsychologicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('defense_mechanism', 'Defense Mechanism'), ('archetype', 'Jungian Archetype'), ('cognitive_bias', 'Cognitive Bias'), ('emotional_trait', 'Emotional Trait'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceTagWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1, help_text="Signed contribution to the reader's score for this tag when this choice is picked.")),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.choice')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.psychologicaltag')),
            ],
            options={
                'unique_together': {('choice', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='psychological_tags',
            field=models.ManyToManyField(blank=True, related_name='choices', through='story.ChoiceTagWeight', to='story.psychologicaltag'),
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Stable identifier used by the Flutter client and content tools.', max_length=255, unique=True)),
                ('text_content', models.TextField()),
                ('node_type', models.CharField(choices=[('standard', 'Standard narrative'), ('choice_point', 'Choice point'), ('reflection', 'Psychological reflection'), ('ending', 'Ending')], default='standard', max_length=20)),
                ('is_ending', models.BooleanField(default=False, help_text='True if reaching this node terminates the current story path.')),
                ('ending_label', models.CharField(blank=True, help_text="e.g. 'The Shadow Accepted', 'Denial Loop' — only used when is_ending=True.", max_length=255)),
                ('is_start', models.BooleanField(default=False, help_text='Marks the node a fresh ReaderProgress should begin at. Exactly one per story.')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Authoring-time ordering within a chapter; not used for graph traversal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chapter_title', 'order_index'],
                'indexes': [models.Index(fields=['node_type'], name='story_story_node_ty_3274f3_idx'), models.Index(fields=['is_ending'], name='story_story_is_endi_1e91f7_idx'), models.Index(fields=['chapter_title', 'order_index'], name='story_story_chapter_a7c4b4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_start', True)), fields=('is_start',), name='only_one_start_node')],
            },
        ),
        migrations.CreateModel(
            name='ReaderProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psychological_profile', models.JSONField(blank=True, default=dict, help_text="Denormalized cache of accumulated tag scores, e.g. {'rationalization': 4, 'projection': -1}. Derived from ChoiceLog + ChoiceTagWeight, kept here for fast reads.")),
                ('flags', models.JSONField(blank=True, default=list, help_text='Narrative flags collected so far, used to gate Choice.requires_flag.')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers_here', to='story.storynode')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='story.choice')),
                ('reader_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_history', to='story.readerprogress')),
                ('node_at_time', models.ForeignKey(help_text='Snapshot of the source node at choice-time, in case the graph is edited later.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='story.storynode')),
            ],
            options={
                'ordering': ['reader_progress', 'made_at'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_choices', to='story.storynode'),
        ),
        migrations.AddField(
            model_name='choice',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='story.storynode'),
        ),
        migrations.AddIndex(
            model_name='readerprogress',
            index=models.Index(fields=['user', 'is_completed'], name='story_reade_user_id_39c751_idx'),
        ),
        migrations.AddIndex(
            model_name='readerprogress',
            index=models.Index(fields=['last_active_at'], name='story_reade_last_ac_979c41_idx'),
        ),
        migrations.AddConstraint(
            model_name='readerprogress',
            constraint=models.UniqueConstraint(fields=('user',), name='one_active_progress_per_user'),
        ),
        migrations.AddIndex(
            model_name='choicelog',
            index=models.Index(fields=['reader_progress', 'made_at'], name='story_choic_reader__94b8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['source_node', 'order_index'], name='story_choic_source__d3d147_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['target_node'], name='story_choic_target__4ddaca_idx'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.CheckConstraint(condition=models.Q(('source_node', models.F('target_node')), _negated=True), name='choice_no_self_loop'),
        ),
    ]
