# Generated by Django 5.2.17 on 2026-09-06 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=500)),
                ('question_text', models.CharField(blank=True, help_text="Optional interpretive prompt shown above the options, e.g. 'What do you think she is avoiding?'", max_length=500)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('requires_flag', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_node', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='PsychologicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('defense_mechanism', 'Defense Mechanism'), ('archetype', 'Jungian Archetype'), ('cognitive_bias', 'Cognitive Bias'), ('attribution', 'Attribution Style'), ('emotional_trait', 'Emotional Trait'), ('other', 'Other')], default='other', max_length=32)),
                ('reader_facing_description', models.TextField(blank=True, help_text="Non-clinical phrasing shown to the reader, e.g. 'You tended to read ambiguous silence as rejection.'")),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=15, help_text='Approximate reading time shown to readers, e.g. 10-25.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Identifier used by clients and authoring tools; unique within its StoryVersion.', max_length=255)),
                ('text_content', models.TextField()),
                ('node_type', models.CharField(choices=[('standard', 'Standard narrative'), ('choice_point', 'Choice point'), ('reflection', 'Psychological reflection'), ('ending', 'Ending')], default='standard', max_length=20)),
                ('is_ending', models.BooleanField(default=False)),
                ('ending_label', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['story_version', 'chapter_title', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='StoryTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceTagWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.choice')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.psychologicaltag')),
            ],
            options={
                'unique_together': {('choice', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='psychological_tags',
            field=models.ManyToManyField(blank=True, related_name='choices', through='story.ChoiceTagWeight', to='story.psychologicaltag'),
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.PositiveIntegerField(default=1, help_text='1 for the first read, 2+ for each replay of the same StoryVersion.')),
                ('psychological_profile', models.JSONField(blank=True, default=dict, help_text="Cached tag-slug -> score tally for this run, e.g. {'rejection_assumption': 4}.")),
                ('flags', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers_here', to='story.storynode')),
            ],
            options={
                'ordering': ['user', 'story_version', 'run_number'],
            },
        ),
        migrations.CreateModel(
            name='ReaderChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='story.choice')),
                ('reading_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_history', to='story.readingsession')),
                ('node_at_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='story.storynode')),
            ],
            options={
                'ordering': ['reading_session', 'made_at'],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text="Reader-facing summary, e.g. 'You repeatedly interpreted silence as rejection.'")),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reading_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='story.readingsession')),
                ('strongest_tag', models.ForeignKey(blank=True, help_text='The tag with the highest accumulated weight this run, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='story.psychologicaltag')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_choices', to='story.storynode'),
        ),
        migrations.AddField(
            model_name='choice',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='story.storynode'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='story.story')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='story.storynode')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='stories', to='story.storytheme'),
        ),
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_node', models.ForeignKey(blank=True, help_text='The node a fresh ReadingSession begins at. Set once authoring is complete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='story.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='story.story')),
            ],
            options={
                'ordering': ['story', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='storynode',
            name='story_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='story.storyversion'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='story_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_sessions', to='story.storyversion'),
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='story.psychologicaltag')),
                ('reader_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='story.readerchoice')),
                ('reading_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='story.readingsession')),
            ],
            options={
                'ordering': ['reading_session', 'created_at'],
                'indexes': [models.Index(fields=['reading_session', 'tag'], name='story_inter_reading_879c92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='readerchoice',
            index=models.Index(fields=['reading_session', 'made_at'], name='story_reade_reading_ce63dd_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['source_node', 'order_index'], name='story_choic_source__d3d147_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['target_node'], name='story_choic_target__4ddaca_idx'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.CheckConstraint(condition=models.Q(('source_node', models.F('target_node')), _negated=True), name='choice_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='one_bookmark_per_user_per_story'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status'], name='story_story_status_fbdfa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyversion',
            constraint=models.UniqueConstraint(fields=('story', 'version_number'), name='unique_version_per_story'),
        ),
        migrations.AddIndex(
            model_name='storynode',
            index=models.Index(fields=['story_version', 'node_type'], name='story_story_story_v_1cd186_idx'),
        ),
        migrations.AddIndex(
            model_name='storynode',
            index=models.Index(fields=['is_ending'], name='story_story_is_endi_1e91f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='storynode',
            constraint=models.UniqueConstraint(fields=('story_version', 'slug'), name='unique_slug_per_story_version'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'story_version', 'is_completed'], name='story_readi_user_id_ac87f6_idx'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['last_active_at'], name='story_readi_last_ac_5c535e_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(fields=('user', 'story_version', 'run_number'), name='unique_run_per_user_per_story_version'),
        ),
    ]
